package com.mobiussoftware.iotbroker.network;

public enum ConnectionState
{
	NONE,CHANNEL_CREATING,CHANNEL_ESTABLISHED,CHANNEL_FAILED,CONNECTING,CONNECTION_ESTABLISHED,CONNECTION_FAILED,CONNECTION_LOST
}